from __future__ import annotations

from dataclasses import dataclass
from typing import Literal

AddressingMode65C02 = Literal[
    "imp",
    "acc",
    "imm",
    "rel",
    "abs",
    "absx",
    "absy",
    "ind",
    "iax",
    "zp",
    "zpx",
    "zpy",
    "indx",
    "indy",
    "izp",
    "zprel",
]


@dataclass(frozen=True)
class Opcode65C02:
    mnemonic: str
    mode: AddressingMode65C02
    length: int


_MODE_LENGTHS: dict[AddressingMode65C02, int] = {
    "imp": 1,
    "acc": 1,
    "imm": 2,
    "rel": 2,
    "abs": 3,
    "absx": 3,
    "absy": 3,
    "ind": 3,
    "iax": 3,
    "zp": 2,
    "zpx": 2,
    "zpy": 2,
    "indx": 2,
    "indy": 2,
    "izp": 2,
    "zprel": 3,
}


def _op(mnemonic: str, mode: AddressingMode65C02) -> Opcode65C02:
    return Opcode65C02(mnemonic=mnemonic, mode=mode, length=_MODE_LENGTHS[mode])


# Complete WDC/Rockwell 65C02 opcode matrix.
# Includes Rockwell/WDC bit opcodes (RMB/SMB/BBR/BBS) and WDC WAI/STP.
_ROWS: list[list[tuple[str, AddressingMode65C02]]] = [
    [
        ("BRK", "imm"),
        ("ORA", "indx"),
        ("NOP", "imm"),
        ("NOP", "imp"),
        ("TSB", "zp"),
        ("ORA", "zp"),
        ("ASL", "zp"),
        ("RMB0", "zp"),
        ("PHP", "imp"),
        ("ORA", "imm"),
        ("ASL", "acc"),
        ("NOP", "imp"),
        ("TSB", "abs"),
        ("ORA", "abs"),
        ("ASL", "abs"),
        ("BBR0", "zprel"),
    ],
    [
        ("BPL", "rel"),
        ("ORA", "indy"),
        ("ORA", "izp"),
        ("NOP", "imp"),
        ("TRB", "zp"),
        ("ORA", "zpx"),
        ("ASL", "zpx"),
        ("RMB1", "zp"),
        ("CLC", "imp"),
        ("ORA", "absy"),
        ("INC", "acc"),
        ("NOP", "imp"),
        ("TRB", "abs"),
        ("ORA", "absx"),
        ("ASL", "absx"),
        ("BBR1", "zprel"),
    ],
    [
        ("JSR", "abs"),
        ("AND", "indx"),
        ("NOP", "imm"),
        ("NOP", "imp"),
        ("BIT", "zp"),
        ("AND", "zp"),
        ("ROL", "zp"),
        ("RMB2", "zp"),
        ("PLP", "imp"),
        ("AND", "imm"),
        ("ROL", "acc"),
        ("NOP", "imp"),
        ("BIT", "abs"),
        ("AND", "abs"),
        ("ROL", "abs"),
        ("BBR2", "zprel"),
    ],
    [
        ("BMI", "rel"),
        ("AND", "indy"),
        ("AND", "izp"),
        ("NOP", "imp"),
        ("BIT", "zpx"),
        ("AND", "zpx"),
        ("ROL", "zpx"),
        ("RMB3", "zp"),
        ("SEC", "imp"),
        ("AND", "absy"),
        ("DEC", "acc"),
        ("NOP", "imp"),
        ("BIT", "absx"),
        ("AND", "absx"),
        ("ROL", "absx"),
        ("BBR3", "zprel"),
    ],
    [
        ("RTI", "imp"),
        ("EOR", "indx"),
        ("NOP", "imm"),
        ("NOP", "imp"),
        ("NOP", "zp"),
        ("EOR", "zp"),
        ("LSR", "zp"),
        ("RMB4", "zp"),
        ("PHA", "imp"),
        ("EOR", "imm"),
        ("LSR", "acc"),
        ("NOP", "imp"),
        ("JMP", "abs"),
        ("EOR", "abs"),
        ("LSR", "abs"),
        ("BBR4", "zprel"),
    ],
    [
        ("BVC", "rel"),
        ("EOR", "indy"),
        ("EOR", "izp"),
        ("NOP", "imp"),
        ("NOP", "zpx"),
        ("EOR", "zpx"),
        ("LSR", "zpx"),
        ("RMB5", "zp"),
        ("CLI", "imp"),
        ("EOR", "absy"),
        ("PHY", "imp"),
        ("NOP", "imp"),
        ("NOP", "abs"),
        ("EOR", "absx"),
        ("LSR", "absx"),
        ("BBR5", "zprel"),
    ],
    [
        ("RTS", "imp"),
        ("ADC", "indx"),
        ("NOP", "imm"),
        ("NOP", "imp"),
        ("STZ", "zp"),
        ("ADC", "zp"),
        ("ROR", "zp"),
        ("RMB6", "zp"),
        ("PLA", "imp"),
        ("ADC", "imm"),
        ("ROR", "acc"),
        ("NOP", "imp"),
        ("JMP", "ind"),
        ("ADC", "abs"),
        ("ROR", "abs"),
        ("BBR6", "zprel"),
    ],
    [
        ("BVS", "rel"),
        ("ADC", "indy"),
        ("ADC", "izp"),
        ("NOP", "imp"),
        ("STZ", "zpx"),
        ("ADC", "zpx"),
        ("ROR", "zpx"),
        ("RMB7", "zp"),
        ("SEI", "imp"),
        ("ADC", "absy"),
        ("PLY", "imp"),
        ("NOP", "imp"),
        ("JMP", "iax"),
        ("ADC", "absx"),
        ("ROR", "absx"),
        ("BBR7", "zprel"),
    ],
    [
        ("BRA", "rel"),
        ("STA", "indx"),
        ("NOP", "imm"),
        ("NOP", "imp"),
        ("STY", "zp"),
        ("STA", "zp"),
        ("STX", "zp"),
        ("SMB0", "zp"),
        ("DEY", "imp"),
        ("BIT", "imm"),
        ("TXA", "imp"),
        ("NOP", "imp"),
        ("STY", "abs"),
        ("STA", "abs"),
        ("STX", "abs"),
        ("BBS0", "zprel"),
    ],
    [
        ("BCC", "rel"),
        ("STA", "indy"),
        ("STA", "izp"),
        ("NOP", "imp"),
        ("STY", "zpx"),
        ("STA", "zpx"),
        ("STX", "zpy"),
        ("SMB1", "zp"),
        ("TYA", "imp"),
        ("STA", "absy"),
        ("TXS", "imp"),
        ("NOP", "imp"),
        ("STZ", "abs"),
        ("STA", "absx"),
        ("STZ", "absx"),
        ("BBS1", "zprel"),
    ],
    [
        ("LDY", "imm"),
        ("LDA", "indx"),
        ("LDX", "imm"),
        ("NOP", "imp"),
        ("LDY", "zp"),
        ("LDA", "zp"),
        ("LDX", "zp"),
        ("SMB2", "zp"),
        ("TAY", "imp"),
        ("LDA", "imm"),
        ("TAX", "imp"),
        ("NOP", "imp"),
        ("LDY", "abs"),
        ("LDA", "abs"),
        ("LDX", "abs"),
        ("BBS2", "zprel"),
    ],
    [
        ("BCS", "rel"),
        ("LDA", "indy"),
        ("LDA", "izp"),
        ("NOP", "imp"),
        ("LDY", "zpx"),
        ("LDA", "zpx"),
        ("LDX", "zpy"),
        ("SMB3", "zp"),
        ("CLV", "imp"),
        ("LDA", "absy"),
        ("TSX", "imp"),
        ("NOP", "imp"),
        ("LDY", "absx"),
        ("LDA", "absx"),
        ("LDX", "absy"),
        ("BBS3", "zprel"),
    ],
    [
        ("CPY", "imm"),
        ("CMP", "indx"),
        ("NOP", "imm"),
        ("NOP", "imp"),
        ("CPY", "zp"),
        ("CMP", "zp"),
        ("DEC", "zp"),
        ("SMB4", "zp"),
        ("INY", "imp"),
        ("CMP", "imm"),
        ("DEX", "imp"),
        ("WAI", "imp"),
        ("CPY", "abs"),
        ("CMP", "abs"),
        ("DEC", "abs"),
        ("BBS4", "zprel"),
    ],
    [
        ("BNE", "rel"),
        ("CMP", "indy"),
        ("CMP", "izp"),
        ("NOP", "imp"),
        ("NOP", "zpx"),
        ("CMP", "zpx"),
        ("DEC", "zpx"),
        ("SMB5", "zp"),
        ("CLD", "imp"),
        ("CMP", "absy"),
        ("PHX", "imp"),
        ("STP", "imp"),
        ("NOP", "abs"),
        ("CMP", "absx"),
        ("DEC", "absx"),
        ("BBS5", "zprel"),
    ],
    [
        ("CPX", "imm"),
        ("SBC", "indx"),
        ("NOP", "imm"),
        ("NOP", "imp"),
        ("CPX", "zp"),
        ("SBC", "zp"),
        ("INC", "zp"),
        ("SMB6", "zp"),
        ("INX", "imp"),
        ("SBC", "imm"),
        ("NOP", "imp"),
        ("NOP", "imp"),
        ("CPX", "abs"),
        ("SBC", "abs"),
        ("INC", "abs"),
        ("BBS6", "zprel"),
    ],
    [
        ("BEQ", "rel"),
        ("SBC", "indy"),
        ("SBC", "izp"),
        ("NOP", "imp"),
        ("NOP", "zpx"),
        ("SBC", "zpx"),
        ("INC", "zpx"),
        ("SMB7", "zp"),
        ("SED", "imp"),
        ("SBC", "absy"),
        ("PLX", "imp"),
        ("NOP", "imp"),
        ("NOP", "abs"),
        ("SBC", "absx"),
        ("INC", "absx"),
        ("BBS7", "zprel"),
    ],
]


OPCODES_65C02: dict[int, Opcode65C02] = {}
for hi, row in enumerate(_ROWS):
    if len(row) != 16:
        raise RuntimeError(f"invalid 65C02 opcode row length at {hi:02X}")
    for lo, (mnemonic, mode) in enumerate(row):
        OPCODES_65C02[(hi << 4) | lo] = _op(mnemonic, mode)

if len(OPCODES_65C02) != 0x100:
    raise RuntimeError("65C02 opcode map must contain 256 entries")
